### ISSUE TITLE
how to record a video during training

### ISSUE THREAD

**Issue by BIT-KaiYu** [ETH-PBL/TC-Driver#1]
how to record a video during training

**Comment by niciBume** [comment]
Can you be more specific?

**Comment by BIT-KaiYu** [comment]
Thank you. When I ran your code, I discovered the videos in the TC-Driver/TC_Driver/train/recording/ directory and was very interested. When I ran train.py, I set record_video to True and modified the relevant code. The final generated video has no pictures.

**Comment by niciBume** [comment]
This is usually a problem with mismatching gym versions. Are your dependencies matching these versions?
https://github.com/ETH-PBL/TC-Driver/blob/main/Gym/requirements.txt

**Comment by BIT-KaiYu** [comment]
The environment is exactly the same. Could this be related to the fact that I commented out the code about `self.visualize` in the `TC-Driver/Gym/gym/f110_gym/envs/f110_rl_env.py`. This was the only change I made, as it resulted in the error: AttributeError: 'RLF110Env' object has no attribute 'create_obs_dict'

**Comment by niciBume** [comment]
It sounds relevant to visualization. We are working on a new version of the TC-Driver gym, which should be fixing this issue in the meanwhile.

**Comment by BIT-KaiYu** [comment]
Thank you, I will continue to pay attention.

**Comment by eghignone** [comment]
@BIT-KaiYu I have added a missing function and fixed an installation requirement that was worng. This should fix the video recording (I tested train.py and obtained such a recording). 

While this is not the new version we are working on that @niciBume mentioned, this should fix at least the recording problem

**Comment by BIT-KaiYu** [comment]
I'm sorry to tell you that the problem still exists. Maybe there is a problem with my environment [requirements.txt](https://github.com/ETH-PBL/TC-Driver/files/15127976/requirements.txt). Thank you anyway.

**Comment by eghignone** [comment]
Thank you for providing us with the requirements.txt file, I imagine that is the dump of your currently installed python packages. From it, it looks like most of the packages are the same version as those in the environment I tested the code, aside for the `tf` which is in my case `tf==1.13.2`, but I doubt this might be the source of the problem.

Could you provide us with more information? Specifically
- what specific command you have tried to run
- what is the output once you run such command
- what are you expecting from the command
